/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    tags: Tag;
    categories: Category;
    personas: Persona;
    contentPlans: ContentPlan;
    contentPlanTransactions: ContentPlanTransaction;
    'contact-details': ContactDetail;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    contentPlans: ContentPlansSelect<false> | ContentPlansSelect<true>;
    contentPlanTransactions: ContentPlanTransactionsSelect<false> | ContentPlanTransactionsSelect<true>;
    'contact-details': ContactDetailsSelect<false> | ContactDetailsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    site: Site;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role for access control
   */
  role: 'admin' | 'editor' | 'user';
  /**
   * Select a persona and optionally customize its profile for this user
   */
  persona?: {
    /**
     * Choose a base persona from the predefined list
     */
    selectedPersona?: (number | null) | Persona;
    /**
     * Snapshot of persona details that you can customize per user
     */
    profile?: {
      name?: string | null;
      category?: string | null;
      focus?: string | null;
      strengths?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      uses?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
      personality?: {
        tone?: string | null;
        voice_style?: string | null;
        motivations?: string | null;
        audience_perception?: string | null;
      };
    };
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage predefined personas selectable on user profiles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: number;
  /**
   * Persona name (e.g., Community Copywriter)
   */
  name: string;
  /**
   * Category (e.g., Emerging / Niche)
   */
  category?: string | null;
  /**
   * Primary focus of the persona
   */
  focus?: string | null;
  /**
   * Key strengths of the persona
   */
  strengths?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Typical use cases
   */
  uses?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  personality?: {
    tone?: string | null;
    voice_style?: string | null;
    motivations?: string | null;
    audience_perception?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage blog posts and articles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The main title of the post
   */
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Brief description of the post (used for meta description if not overridden)
   */
  excerpt?: string | null;
  /**
   * Main image for the post (used for Open Graph and Twitter cards)
   */
  featuredImage?: (number | null) | Media;
  /**
   * The main content of the post
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Temporary draft text for the post
   */
  postContentDraft?: string | null;
  /**
   * Author of this post
   */
  author?: (number | null) | User;
  /**
   * Tags associated with this post
   */
  tags?: (number | Tag)[] | null;
  /**
   * Categories for this post
   */
  categories?: (number | Category)[] | null;
  /**
   * When this post was first published
   */
  datePublished?: string | null;
  /**
   * When this post was last modified
   */
  dateModified?: string | null;
  /**
   * Target publish date (from Content Plan)
   */
  plannedPublishDate?: string | null;
  /**
   * Publication status of the post
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Automatically computed metadata
   */
  metadata?: {
    /**
     * Estimated reading time in minutes
     */
    readingTime?: number | null;
    /**
     * Total word count
     */
    wordCount?: number | null;
    /**
     * Last modification timestamp
     */
    lastModified?: string | null;
  };
  /**
   * Override site-wide SEO settings for this specific post
   */
  seo?: {
    /**
     * Override the page title (defaults to post title)
     */
    pageTitle?: string | null;
    /**
     * Override meta description (defaults to excerpt)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for this post
     */
    metaKeywords?: string | null;
    /**
     * Override canonical URL (defaults to post URL)
     */
    canonicalURL?: string | null;
  };
  /**
   * Override Open Graph settings
   */
  openGraph?: {
    /**
     * Override Open Graph title
     */
    ogTitle?: string | null;
    /**
     * Override Open Graph description
     */
    ogDescription?: string | null;
    /**
     * Override Open Graph image (defaults to featured image)
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Override Twitter card settings
   */
  twitter?: {
    /**
     * Override Twitter card title
     */
    twitterTitle?: string | null;
    /**
     * Override Twitter card description
     */
    twitterDescription?: string | null;
    /**
     * Override Twitter card image (defaults to featured image)
     */
    twitterImage?: (number | null) | Media;
  };
  /**
   * Override structured data settings
   */
  jsonld?: {
    /**
     * Override schema headline (defaults to title)
     */
    headline?: string | null;
    /**
     * Override schema description
     */
    schemaDescription?: string | null;
    /**
     * Automatically calculated word count
     */
    wordCount?: number | null;
  };
  seoComputed?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage tags for posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * The name of the tag
   */
  name: string;
  /**
   * URL-friendly version of the tag name
   */
  slug: string;
  /**
   * Optional description for the tag
   */
  description?: string | null;
  /**
   * Hex color code for the tag (e.g., #FF5733)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage categories for posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The name of the category
   */
  name: string;
  /**
   * URL-friendly version of the category name
   */
  slug: string;
  /**
   * Optional description for the category
   */
  description?: string | null;
  /**
   * Hex color code for the category (e.g., #FF5733)
   */
  color?: string | null;
  /**
   * Parent category (for hierarchical categories)
   */
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * Content planning and organization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentPlans".
 */
export interface ContentPlan {
  id: number;
  owner: number | User;
  status?: ('draft' | 'active' | 'completed' | 'archived') | null;
  /**
   * Main topic or theme for this content plan
   */
  topic: string;
  /**
   * Individual content pieces within this plan
   */
  contentItems?:
    | {
        /**
         * Title of the content piece (max 200 characters)
         */
        title: string;
        /**
         * URL-friendly version of the title (auto-generated, but editable)
         */
        slug: string;
        /**
         * Detailed description of the content (max 1000 characters, supports markdown)
         */
        description?: string | null;
        /**
         * SEO keywords and tags for this content
         */
        keywords?:
          | {
              keyword: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Generation prompt to guide content creation
         */
        prompt?: string | null;
        /**
         * Intended audience for this piece
         */
        audience?: string | null;
        /**
         * Primary goal or outcome for this content
         */
        goal?: string | null;
        /**
         * Target region or locale
         */
        region?: string | null;
        /**
         * Target word count for the piece
         */
        word_count?: number | null;
        /**
         * One or more prompts for generating visuals
         */
        image_prompts?:
          | {
              prompt: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Brief description of this content plan
   */
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Additional notes and planning details
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Transaction logs for content plan operations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentPlanTransactions".
 */
export interface ContentPlanTransaction {
  id: number;
  /**
   * Unique identifier for the transaction
   */
  transactionId: string;
  /**
   * ID of the content plan being modified
   */
  contentPlanId: number;
  /**
   * Type of operation being performed
   */
  operation: 'save_generated' | 'update' | 'delete';
  /**
   * Current status of the transaction
   */
  status: 'pending' | 'in_progress' | 'committed' | 'failed' | 'rolled_back';
  /**
   * Error message if the transaction failed
   */
  errorDetails?: string | null;
  /**
   * Additional metadata about the transaction
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of retry attempts made
   */
  retryCount?: number | null;
  /**
   * Total execution time in milliseconds
   */
  executionTimeMs?: number | null;
  /**
   * When the transaction was completed (success or failure)
   */
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Contact Details in a structure compatible with .trae/documents/contact.md JSON-LD
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-details".
 */
export interface ContactDetail {
  id: number;
  /**
   * Used as the admin title. Recommend matching Organization name.
   */
  title: string;
  organization: {
    orgId: string;
    name: string;
    url: string;
    logo?: string | null;
    email: string;
    telephone: string;
    areaServed?:
      | {
          type: 'Country' | 'City';
          name: string;
          id?: string | null;
        }[]
      | null;
    sameAs?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    contactPoint?:
      | {
          contactType: string;
          name?: string | null;
          telephone: string;
          email?: string | null;
          availableLanguage?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          areaServed?: string | null;
          hoursAvailable?: {
            dayOfWeek?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday') | null;
            opens?: string | null;
            closes?: string | null;
          };
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    department?:
      | {
          id: string;
        }[]
      | null;
  };
  hq: {
    hqId: string;
    name: string;
    image?: string | null;
    telephone: string;
    email?: string | null;
    address: {
      streetAddress: string;
      addressLocality: string;
      addressRegion: string;
      postalCode: string;
      addressCountry: string;
    };
    geo: {
      latitude: number;
      longitude: number;
    };
    hasMap?: string | null;
    openingHoursSpecification?:
      | {
          dayOfWeek?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday') | null;
          opens?: string | null;
          closes?: string | null;
          id?: string | null;
        }[]
      | null;
    publicAccess?: boolean | null;
    amenityFeature?:
      | {
          name: string;
          value?: boolean | null;
          id?: string | null;
        }[]
      | null;
    areaServed: {
      geoMidpoint: {
        latitude: number;
        longitude: number;
      };
      geoRadius: number;
    };
    paymentAccepted?: string | null;
    currenciesAccepted?: string | null;
    priceRange?: string | null;
  };
  persons?:
    | {
        personId: string;
        name: string;
        jobTitle: string;
        telephone: string;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  webPage: {
    webPageId: string;
    url: string;
    name: string;
    description: string;
    primaryImageOfPage?: string | null;
    potentialAction?:
      | {
          actions?:
            | (
                | {
                    target?: {
                      urlTemplate?: string | null;
                      actionPlatform?:
                        | ('http://schema.org/DesktopWebPlatform' | 'http://schema.org/MobileWebPlatform')
                        | null;
                      inLanguage?: string | null;
                    };
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'ContactAction';
                  }
                | {
                    name?: string | null;
                    target?: {
                      urlTemplate?: string | null;
                      actionPlatform?:
                        | ('http://schema.org/DesktopWebPlatform' | 'http://schema.org/MobileWebPlatform')
                        | null;
                    };
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'CommunicateAction';
                  }
              )[]
            | null;
          id?: string | null;
        }[]
      | null;
    inLanguage?: string | null;
  };
  breadcrumb: {
    breadcrumbId: string;
    items?:
      | {
          position: number;
          name: string;
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    faqId: string;
    mainEntity?:
      | {
          name: string;
          acceptedAnswer: string;
          id?: string | null;
        }[]
      | null;
  };
  website: {
    websiteId: string;
    url: string;
    name: string;
    sameAs?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    inLanguage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'personas';
        value: number | Persona;
      } | null)
    | ({
        relationTo: 'contentPlans';
        value: number | ContentPlan;
      } | null)
    | ({
        relationTo: 'contentPlanTransactions';
        value: number | ContentPlanTransaction;
      } | null)
    | ({
        relationTo: 'contact-details';
        value: number | ContactDetail;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  persona?:
    | T
    | {
        selectedPersona?: T;
        profile?:
          | T
          | {
              name?: T;
              category?: T;
              focus?: T;
              strengths?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              uses?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              personality?:
                | T
                | {
                    tone?: T;
                    voice_style?: T;
                    motivations?: T;
                    audience_perception?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  postContentDraft?: T;
  author?: T;
  tags?: T;
  categories?: T;
  datePublished?: T;
  dateModified?: T;
  plannedPublishDate?: T;
  status?: T;
  metadata?:
    | T
    | {
        readingTime?: T;
        wordCount?: T;
        lastModified?: T;
      };
  seo?:
    | T
    | {
        pageTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        canonicalURL?: T;
      };
  openGraph?:
    | T
    | {
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  twitter?:
    | T
    | {
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
      };
  jsonld?:
    | T
    | {
        headline?: T;
        schemaDescription?: T;
        wordCount?: T;
      };
  seoComputed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  focus?: T;
  strengths?:
    | T
    | {
        value?: T;
        id?: T;
      };
  uses?:
    | T
    | {
        value?: T;
        id?: T;
      };
  personality?:
    | T
    | {
        tone?: T;
        voice_style?: T;
        motivations?: T;
        audience_perception?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentPlans_select".
 */
export interface ContentPlansSelect<T extends boolean = true> {
  owner?: T;
  status?: T;
  topic?: T;
  contentItems?:
    | T
    | {
        title?: T;
        slug?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        prompt?: T;
        audience?: T;
        goal?: T;
        region?: T;
        word_count?: T;
        image_prompts?:
          | T
          | {
              prompt?: T;
              id?: T;
            };
        id?: T;
      };
  description?: T;
  startDate?: T;
  endDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentPlanTransactions_select".
 */
export interface ContentPlanTransactionsSelect<T extends boolean = true> {
  transactionId?: T;
  contentPlanId?: T;
  operation?: T;
  status?: T;
  errorDetails?: T;
  metadata?: T;
  retryCount?: T;
  executionTimeMs?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-details_select".
 */
export interface ContactDetailsSelect<T extends boolean = true> {
  title?: T;
  organization?:
    | T
    | {
        orgId?: T;
        name?: T;
        url?: T;
        logo?: T;
        email?: T;
        telephone?: T;
        areaServed?:
          | T
          | {
              type?: T;
              name?: T;
              id?: T;
            };
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
        contactPoint?:
          | T
          | {
              contactType?: T;
              name?: T;
              telephone?: T;
              email?: T;
              availableLanguage?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              areaServed?: T;
              hoursAvailable?:
                | T
                | {
                    dayOfWeek?: T;
                    opens?: T;
                    closes?: T;
                  };
              url?: T;
              id?: T;
            };
        department?:
          | T
          | {
              id?: T;
            };
      };
  hq?:
    | T
    | {
        hqId?: T;
        name?: T;
        image?: T;
        telephone?: T;
        email?: T;
        address?:
          | T
          | {
              streetAddress?: T;
              addressLocality?: T;
              addressRegion?: T;
              postalCode?: T;
              addressCountry?: T;
            };
        geo?:
          | T
          | {
              latitude?: T;
              longitude?: T;
            };
        hasMap?: T;
        openingHoursSpecification?:
          | T
          | {
              dayOfWeek?: T;
              opens?: T;
              closes?: T;
              id?: T;
            };
        publicAccess?: T;
        amenityFeature?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
        areaServed?:
          | T
          | {
              geoMidpoint?:
                | T
                | {
                    latitude?: T;
                    longitude?: T;
                  };
              geoRadius?: T;
            };
        paymentAccepted?: T;
        currenciesAccepted?: T;
        priceRange?: T;
      };
  persons?:
    | T
    | {
        personId?: T;
        name?: T;
        jobTitle?: T;
        telephone?: T;
        email?: T;
        id?: T;
      };
  webPage?:
    | T
    | {
        webPageId?: T;
        url?: T;
        name?: T;
        description?: T;
        primaryImageOfPage?: T;
        potentialAction?:
          | T
          | {
              actions?:
                | T
                | {
                    ContactAction?:
                      | T
                      | {
                          target?:
                            | T
                            | {
                                urlTemplate?: T;
                                actionPlatform?: T;
                                inLanguage?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    CommunicateAction?:
                      | T
                      | {
                          name?: T;
                          target?:
                            | T
                            | {
                                urlTemplate?: T;
                                actionPlatform?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
            };
        inLanguage?: T;
      };
  breadcrumb?:
    | T
    | {
        breadcrumbId?: T;
        items?:
          | T
          | {
              position?: T;
              name?: T;
              item?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        faqId?: T;
        mainEntity?:
          | T
          | {
              name?: T;
              acceptedAnswer?: T;
              id?: T;
            };
      };
  website?:
    | T
    | {
        websiteId?: T;
        url?: T;
        name?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
        inLanguage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site settings and defaults for SEO, social media, and performance
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  /**
   * The name of your website
   */
  siteName: string;
  /**
   * The base URL of your website (without trailing slash)
   */
  siteUrl: string;
  /**
   * Default description used for meta tags and social media
   */
  siteDescription?: string | null;
  /**
   * Short tagline or slogan for your site
   */
  siteTagline?: string | null;
  seoDefaults?: {
    /**
     * Default author for meta tags
     */
    metaAuthor?: string | null;
    /**
     * Default robots directive for search engines
     */
    robots?: string | null;
    /**
     * Character encoding for the site
     */
    charset?: string | null;
    /**
     * Default viewport meta tag
     */
    viewport?: string | null;
    /**
     * Theme color for mobile browsers
     */
    themeColor?: string | null;
    /**
     * Default language code
     */
    language?: string | null;
    /**
     * How often search engines should revisit
     */
    revisitAfter?: string | null;
  };
  openGraphDefaults?: {
    /**
     * Site name for Open Graph
     */
    ogSiteName?: string | null;
    /**
     * Default locale for Open Graph
     */
    ogLocale?: string | null;
    /**
     * Default Open Graph type
     */
    ogType?: ('website' | 'article') | null;
    /**
     * Default image for social media sharing (1200x630px recommended)
     */
    defaultOgImage?: (number | null) | Media;
    /**
     * Alt text for the default Open Graph image
     */
    defaultOgImageAlt?: string | null;
  };
  twitterDefaults?: {
    /**
     * Default Twitter Card type
     */
    twitterCard?: ('summary_large_image' | 'summary') | null;
    /**
     * Twitter handle for the site (with @)
     */
    twitterSite?: string | null;
    /**
     * Default Twitter handle for content creator (with @)
     */
    twitterCreator?: string | null;
  };
  schemaDefaults?: {
    /**
     * Enable JSON-LD structured data generation
     */
    generateJSONLD?: boolean | null;
    /**
     * Default schema type for articles
     */
    defaultSchemaType?: ('Article' | 'BlogPosting' | 'NewsArticle') | null;
    /**
     * Default language for schema markup
     */
    inLanguage?: string | null;
    /**
     * Whether content is accessible for free
     */
    isAccessibleForFree?: boolean | null;
    organization?: {
      /**
       * Organization name
       */
      name?: string | null;
      /**
       * Organization website URL
       */
      url?: string | null;
      /**
       * Organization logo
       */
      logo?: (number | null) | Media;
      /**
       * Social media and other profile URLs
       */
      sameAs?:
        | {
            /**
             * Social media profile URL
             */
            url?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    publisher?: {
      /**
       * Publisher name
       */
      name?: string | null;
      /**
       * Publisher logo
       */
      logo?: (number | null) | Media;
    };
    webSite?: {
      /**
       * Website URL
       */
      url?: string | null;
      /**
       * Website name
       */
      name?: string | null;
      searchAction?: {
        /**
         * Search URL template
         */
        target?: string | null;
        /**
         * Query input specification
         */
        queryInput?: string | null;
      };
    };
  };
  /**
   * Favicon (.ico file)
   */
  faviconICO?: (number | null) | Media;
  /**
   * SVG icon for modern browsers
   */
  iconSVG?: (number | null) | Media;
  /**
   * Apple touch icon (180x180px)
   */
  appleTouchIcon?: (number | null) | Media;
  /**
   * Web app manifest file
   */
  webAppManifest?: (number | null) | Media;
  /**
   * CDN domain for static assets
   */
  cdnDomain?: string | null;
  /**
   * Domain for analytics or ads
   */
  analyticsOrAdsDomain?: string | null;
  /**
   * Domains to establish early connections to
   */
  preconnect?:
    | {
        /**
         * URL to preconnect to
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Domains to prefetch DNS for
   */
  dnsPrefetch?:
    | {
        /**
         * Domain to prefetch DNS for
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * RSS feed URL
   */
  rssLink?: string | null;
  /**
   * Google Search Console verification code
   */
  googleSiteVerification?: string | null;
  /**
   * Bing Webmaster Tools verification code
   */
  bingMsValidate?: string | null;
  /**
   * Yandex Webmaster verification code
   */
  yandexVerification?: string | null;
  /**
   * Google Tag Manager ID (GTM-XXXXXXX)
   */
  gtmID?: string | null;
  /**
   * Google Analytics Measurement ID (G-XXXXXXXXXX)
   */
  gaMeasurementID?: string | null;
  /**
   * Facebook Pixel ID
   */
  facebookPixelID?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global site header: logo and navigation links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Shown only when a logo is selected. Defaults to 400px.
   */
  logoWidth?: number | null;
  /**
   * Shown only when a logo is selected. Defaults to 200px.
   */
  logoHeight?: number | null;
  navLinks?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global site footer: navigation and legal links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyrightText?: string | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  siteDescription?: T;
  siteTagline?: T;
  seoDefaults?:
    | T
    | {
        metaAuthor?: T;
        robots?: T;
        charset?: T;
        viewport?: T;
        themeColor?: T;
        language?: T;
        revisitAfter?: T;
      };
  openGraphDefaults?:
    | T
    | {
        ogSiteName?: T;
        ogLocale?: T;
        ogType?: T;
        defaultOgImage?: T;
        defaultOgImageAlt?: T;
      };
  twitterDefaults?:
    | T
    | {
        twitterCard?: T;
        twitterSite?: T;
        twitterCreator?: T;
      };
  schemaDefaults?:
    | T
    | {
        generateJSONLD?: T;
        defaultSchemaType?: T;
        inLanguage?: T;
        isAccessibleForFree?: T;
        organization?:
          | T
          | {
              name?: T;
              url?: T;
              logo?: T;
              sameAs?:
                | T
                | {
                    url?: T;
                    id?: T;
                  };
            };
        publisher?:
          | T
          | {
              name?: T;
              logo?: T;
            };
        webSite?:
          | T
          | {
              url?: T;
              name?: T;
              searchAction?:
                | T
                | {
                    target?: T;
                    queryInput?: T;
                  };
            };
      };
  faviconICO?: T;
  iconSVG?: T;
  appleTouchIcon?: T;
  webAppManifest?: T;
  cdnDomain?: T;
  analyticsOrAdsDomain?: T;
  preconnect?:
    | T
    | {
        href?: T;
        id?: T;
      };
  dnsPrefetch?:
    | T
    | {
        href?: T;
        id?: T;
      };
  rssLink?: T;
  googleSiteVerification?: T;
  bingMsValidate?: T;
  yandexVerification?: T;
  gtmID?: T;
  gaMeasurementID?: T;
  facebookPixelID?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logoWidth?: T;
  logoHeight?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        highlight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}